win message has been added, moving is upgraded
RedEyeCoffee/TheGame pull request #24
Opened 2023-03-29 18:59 UTC by Kris465

1. Слегка видоизменила управление, для удобства
2. Увеличила у игрока урон
3. Переписала метод move() во вьюхе
4. Добавила концовку игре (вывод сообщения, которое поздравляет с победой или проигрышем и завершает игру)
Возможно, логика концовки не очень, скорее всего придется добавлять еще условие гибели игрока, но это уже после того, как мобы начнут отвечать.

2023-04-01 17:01 UTC, lameRER commented on controller.py
> -        print(self.field)
Гууд, изначално даже не обратил внимания, что тут принт подкрался незаметно

2023-04-01 17:09 UTC, lameRER commented on viewconsole.py
> +                    case 'a' | 's' | 'w' | 'd':
нтересная задумка, пришла в голову идея использовать библиотеку 
msvcrt

Это на будующее, когда у игру будет меню
import msvcrt as m
m.getch() # На этом месте программа останавливается и ждёт ввода любого символа, как только символ будет введён, выполнение продолжится БЕЗ НАЖАТИЯ ENTER

2023-04-01 17:29 UTC, lameRER commented on viewconsole.py
> +                move = input(f' Влево(a) Вниз(s) Вверх(w) Вправо(d)\n Атака(e) Выход(ex)\n')
Формат строки тут ненужен

2023-04-01 17:51 UTC, lameRER requested changes
Убрать Формат строки

2023-04-01 17:52 UTC, lameRER commented on viewconsole.py
> +                move = input(f' Влево(a) Вниз(s) Вверх(w) Вправо(d)\n Атака(e) Выход(ex)\n')
Формат строки тут ненужен

2023-04-01 18:48 UTC, Kris465 commented on viewconsole.py
> +                    case 'a' | 's' | 'w' | 'd':
ОГОНЬ! Я себе голову сломала как от интера избавиться. Ты мой герой!

2023-04-01 18:49 UTC, Kris465 commented on controller.py
> -        print(self.field)
Спасибо!)) Я все мечтаю сесь и уже начать писать юнит-тесты...

2023-04-01 18:49 UTC, Kris465 commented on viewconsole.py
> +                move = input(f' Влево(a) Вниз(s) Вверх(w) Вправо(d)\n Атака(e) Выход(ex)\n')
Да, вчера нашла, убрала, а в пулреквесте еще остался(

2023-04-02 01:34 UTC, lameRER approved these changes

2023-04-02 01:49 UTC, merged